'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ScrapReporting.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property _1488511341_icon_27_trash_can() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("_1488511341_icon_27_trash_can", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1	20154	03302015
        '''2	20155	05042015
        '''3	20156	06012015
        '''4	20157	06292015
        '''5	20158	08032015
        '''6	20159	08312015
        '''7	201510	09282015
        '''8	201511	11022015
        '''9	201512	11302015
        '''10	20161	01042016
        '''11	20162	02012016
        '''12	20163	03072016
        '''13	20164	04042016
        '''14	20165	05092016
        '''15	20166	06062016
        '''16	20167	07042016
        '''17	20168	08082016
        '''18	20169	09052016
        '''19	201610	10032016
        '''20	201611	11072016
        '''21	201612	12052016
        '''22	20171	01022017
        '''23	20172	02062017
        '''24	20173	03062017
        '''25	20174	04032017
        '''26	20175	05082017
        '''27	20176	06052017
        '''28 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MonthList() As String
            Get
                Return ResourceManager.GetString("MonthList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!--Olap Javascript--&gt;
        '''&lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;META name=&quot;HandheldFriendly&quot; content=&quot;True&quot;&gt;
        '''&lt;META name=&quot;PalmComputingPlatform&quot; content=&quot;True&quot;&gt;
        '''&lt;TITLE&gt;WebFOCUS Report&lt;/TITLE&gt;
        '''&lt;script language=&apos;javascript&apos;&gt;
        '''var ibiOptions = new Array(&quot;expandByRow&quot;);
        '''var focexurl = &quot;/ibi_apps/WFServlet?IBIF_webapp=/ibi_apps&amp;IBIC_server=EDASERVE&amp;IBIWF_msgviewer=OFF&amp;IBIAPP_app=prodvis&amp;&amp;IBIMR_drill=X,qavistes/qavistes.htm&amp;&quot;;
        '''var fochtmlurl = &quot;/ibi_html&quot;;
        '''var serverLanguage=&apos;en&apos;;
        '''&lt;/script&gt;
        '''&lt;script language=&apos;javascript&apos; src=&apos;/ib [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
